// internal/models/models.go
package models

import (
	"time"

	"github.com/google/uuid"
	"github.com/shopspring/decimal"
)

// ---------------------------------------------------------------------
// Asset / Portfolio Models
// ---------------------------------------------------------------------

type UserBalanceDetail struct {
	TokenID        uuid.UUID       `json:"token_id"`
	Symbol         string          `json:"symbol"`
	Name           string          `json:"name"`
	Balance        decimal.Decimal `json:"balance"`
	PriceUSD       decimal.Decimal `json:"price_usd"`
	ValueUSD       decimal.Decimal `json:"value_usd"`
	PriceChange24h decimal.Decimal `json:"price_change_24h,omitempty"`
}

type PortfolioSummary struct {
	TotalValueUSD decimal.Decimal     `json:"total_value_usd"`
	Balances      []UserBalanceDetail `json:"balances"`
	LastUpdated   time.Time           `json:"last_updated"`
}

type NetworkAssetSummary struct {
	TotalValueLockedUSD decimal.Decimal `json:"total_value_locked_usd"`
	TotalTokenHolders   int64           `json:"total_token_holders"`
	ActiveTokens        int64           `json:"active_tokens"`
	TopHolders          []TopHolder     `json:"top_holders,omitempty"`
}

type TopHolder struct {
	UserID   uuid.UUID       `json:"user_id"`
	Wallet   string          `json:"wallet"`
	Balance  decimal.Decimal `json:"balance"`
	ValueUSD decimal.Decimal `json:"value_usd"`
}

// ---------------------------------------------------------------------
// Badge Models
// ---------------------------------------------------------------------

type BadgeBenefits struct {
	CombatPowerMultiplier decimal.Decimal `json:"combat_power_multiplier,omitempty"`
	GovernanceMultiplier  decimal.Decimal `json:"governance_multiplier,omitempty"`
	MiningBoost           decimal.Decimal `json:"mining_boost,omitempty"`
	LPYieldBoost          decimal.Decimal `json:"lp_yield_boost,omitempty"`
	DailyRewardBonus      decimal.Decimal `json:"daily_reward_bonus,omitempty"`
	ReferralRewardShare   decimal.Decimal `json:"referral_reward_share,omitempty"`
	CustomPermissions     []string        `json:"custom_permissions,omitempty"`
}

type NetworkBadgeStats struct {
	TotalBadges        int64 `json:"total_badges"`
	DistributionByTier []struct {
		Tier  int32 `json:"tier"`
		Count int64 `json:"count"`
	} `json:"distribution_by_tier"`
	MostPopularBadges []interface{} `json:"most_popular_badges"` // Use specific type if available
}

// ---------------------------------------------------------------------
// Block Reward Models
// ---------------------------------------------------------------------

type UserRewardsSummary struct {
	TotalEarned    decimal.Decimal `json:"total_earned"`
	TotalClaimed   decimal.Decimal `json:"total_claimed"`
	PendingRewards decimal.Decimal `json:"pending_rewards"`
	UnclaimedCount int64           `json:"unclaimed_count"`
	LastClaimTime  *time.Time      `json:"last_claim_time,omitempty"`
}

// ---------------------------------------------------------------------
// Combat Power Models
// ---------------------------------------------------------------------

// (CombatPower is generated by SQLC, but we might need additional view models)

// ---------------------------------------------------------------------
// Governance Models
// ---------------------------------------------------------------------

type GovernanceStats struct {
	TotalProposals       int64           `json:"total_proposals"`
	ActiveProposals      int64           `json:"active_proposals"`
	PassedProposals      int64           `json:"passed_proposals"`
	ExecutedProposals    int64           `json:"executed_proposals"`
	TotalVoters          int64           `json:"total_voters"`
	AverageParticipation decimal.Decimal `json:"average_participation"`
}

type CreateProposalParams struct {
	ProposerID   uuid.UUID
	Title        string
	Description  string
	ProposalType string
	VotingEnd    time.Time
	Quorum       decimal.Decimal
	Threshold    decimal.Decimal
}

type VoteResult struct {
	ForVotes        decimal.Decimal `json:"for_votes"`
	AgainstVotes    decimal.Decimal `json:"against_votes"`
	AbstainVotes    decimal.Decimal `json:"abstain_votes"`
	TotalVotes      decimal.Decimal `json:"total_votes"`
	QuorumReached   bool            `json:"quorum_reached"`
	ThresholdPassed bool            `json:"threshold_passed"`
}

// ---------------------------------------------------------------------
// LP / Liquidity Pool Models
// ---------------------------------------------------------------------

type AddLiquidityParams struct {
	UserID  uuid.UUID
	PoolID  uuid.UUID
	Amount0 decimal.Decimal
	Amount1 decimal.Decimal
	TxHash  string
}

type RemoveLiquidityParams struct {
	UserID   uuid.UUID
	PoolID   uuid.UUID
	LpAmount decimal.Decimal
	TxHash   string
}

type PoolStats struct {
	PoolID             uuid.UUID       `json:"pool_id"`
	Name               string          `json:"name"`
	TotalLiquidityUSD  decimal.Decimal `json:"total_liquidity_usd"`
	APR                decimal.Decimal `json:"apr"`
	TotalLpAmount      decimal.Decimal `json:"total_lp_amount"`
	LiquidityProviders int64           `json:"liquidity_providers"`
}

// ---------------------------------------------------------------------
// Mining Models
// ---------------------------------------------------------------------

type MiningEarnings struct {
	StaticRelease       decimal.Decimal `json:"static_release"`
	AccelerationRelease decimal.Decimal `json:"acceleration_release"`
	Total               decimal.Decimal `json:"total"`
}

type UserMiningStats struct {
	Level             int32           `json:"level"`
	StaticRate        decimal.Decimal `json:"static_rate"`
	AccelerationRate  decimal.Decimal `json:"acceleration_rate"`
	TotalMined        decimal.Decimal `json:"total_mined"`
	TodayEarnings     *MiningEarnings `json:"today_earnings,omitempty"`
	YesterdayEarnings decimal.Decimal `json:"yesterday_earnings,omitempty"`
	LastWeekEarnings  decimal.Decimal `json:"last_week_earnings,omitempty"`
	UpgradeCost       decimal.Decimal `json:"upgrade_cost"`
}

// ---------------------------------------------------------------------
// Node / Referral Models
// ---------------------------------------------------------------------

type NetworkNodeStats struct {
	TotalUsers          int64               `json:"total_users"`
	AverageNodeLevel    float64             `json:"average_node_level"`
	HighestNodeLevel    int32               `json:"highest_node_level"`
	NodeHolders         int64               `json:"node_holders"`
	DistributionByLevel []LevelDistribution `json:"distribution_by_level"`
	TopNodes            []interface{}       `json:"top_nodes"` // Use specific type if available
}

type LevelDistribution struct {
	Level     int32 `json:"level"`
	UserCount int64 `json:"user_count"`
}

type UpgradeEligibility struct {
	UserID                uuid.UUID       `json:"user_id"`
	CurrentLevel          int32           `json:"current_level"`
	NextLevel             int32           `json:"next_level"`
	TeamPower             decimal.Decimal `json:"team_power"`
	RequiredTeamPower     decimal.Decimal `json:"required_team_power"`
	DirectReferrals       int32           `json:"direct_referrals"`
	RequiredDirectMembers int32           `json:"required_direct_members"`
	PowerEligible         bool            `json:"power_eligible"`
	MembersEligible       bool            `json:"members_eligible"`
	Eligible              bool            `json:"eligible"`
}

type ReferralEvent struct {
	ID             uuid.UUID       `json:"id"`
	UserID         uuid.UUID       `json:"user_id"`
	ReferrerID     uuid.UUID       `json:"referrer_id"`
	ReferrerWallet string          `json:"referrer_wallet"`
	Amount         decimal.Decimal `json:"amount"`
	TokenSymbol    string          `json:"token_symbol"`
	EarningType    string          `json:"earning_type"`
	CreatedAt      time.Time       `json:"created_at"`
}

// ---------------------------------------------------------------------
// Purchase Models
// ---------------------------------------------------------------------

type SubscribeParams struct {
	UserID       uuid.UUID
	TokenSymbol  string
	Amount       decimal.Decimal
	PaymentToken string
}

// ---------------------------------------------------------------------
// Swap Models
// ---------------------------------------------------------------------

type SwapParams struct {
	UserID    uuid.UUID
	FromToken string
	ToToken   string
	Amount    decimal.Decimal
	TxHash    string
}

type SwapResult struct {
	FromAmount decimal.Decimal `json:"from_amount"`
	ToAmount   decimal.Decimal `json:"to_amount"`
	Rate       decimal.Decimal `json:"rate"`
	TxHash     string          `json:"tx_hash"`
}

type SwapVolumeStats struct {
	TotalVolume24h decimal.Decimal `json:"total_volume_24h"`
	SwapCount24h   int64           `json:"swap_count_24h"`
	VolumeByToken  []interface{}   `json:"volume_by_token"`
	PopularPairs   []interface{}   `json:"popular_pairs"`
}

type UserSwapSummary struct {
	TotalSwapped    decimal.Decimal `json:"total_swapped"`
	SwapCount       int64           `json:"swap_count"`
	MostSwappedFrom string          `json:"most_swapped_from"`
	MostSwappedTo   string          `json:"most_swapped_to"`
}

// ---------------------------------------------------------------------
// Withdrawal Models
// ---------------------------------------------------------------------

type WithdrawalRequestParams struct {
	UserID      uuid.UUID
	TokenSymbol string
	Amount      decimal.Decimal
}

type WithdrawalStatsSummary struct {
	TotalWithdrawals int64           `json:"total_withdrawals"`
	TotalAmount      decimal.Decimal `json:"total_amount"`
	PendingCount     int64           `json:"pending_count"`
	CompletedCount   int64           `json:"completed_count"`
	CancelledCount   int64           `json:"cancelled_count"`
	FailedCount      int64           `json:"failed_count"`
	StatsByToken     []interface{}   `json:"stats_by_token"`
}

// ---------------------------------------------------------------------
// Common / Utility Models
// ---------------------------------------------------------------------

// TimeRange represents a time period for filtering
type TimeRange struct {
	Start time.Time `json:"start"`
	End   time.Time `json:"end"`
}

// IDResponse is a common response for created resources
type IDResponse struct {
	ID interface{} `json:"id"`
}

// MessageResponse is a simple { "message": "..." } response
type MessageResponse struct {
	Message string `json:"message"`
}

// ErrorResponse is used for error responses
type ErrorResponse struct {
	Code    int         `json:"code"`
	Message string      `json:"message"`
	Details interface{} `json:"details,omitempty"`
}
